workflows:
  ios-capacitor-workflow:
    name: iOS Capacitor Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Capacitor build and sync
        script: |
          npm run build || node build.js
          npx cap sync ios
      - name: Set up code signing
        script: |
          # Questo passo verrà configurato tramite l'interfaccia di Codemagic
          # per caricare i certificati e i profili di provisioning.
          echo "Setup code signing in Codemagic UI"
      - name: Build iOS
        script: |
          # Compila il file .ipa
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user_email@example.com # Da cambiare con la tua email
        notify:
          success: true
          failure: true
